import { motion } from "framer-motion";
import { ScanLine, BarChart3, Receipt, LineChart, ShieldCheck, Mail } from "lucide-react";
import { cn } from "@/lib/utils";

const features = [
  {
    title: "AI Receipt Scanning",
    description: "Upload any receipt and our AI instantly extracts amounts, dates, and categorizes the expense.",
    icon: ScanLine,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
  },
  {
    title: "Smart Analytics",
    description: "Visualize your spending patterns with beautiful, interactive charts that update in real-time.",
    icon: BarChart3,
    color: "text-indigo-500",
    bgColor: "bg-indigo-500/10",
  },
  {
    title: "Recurring Transactions",
    description: "Set up subscriptions and regular bills once. FinSight automatically tracks them for you.",
    icon: Receipt,
    color: "text-emerald-500",
    bgColor: "bg-emerald-500/10",
  },
  {
    title: "Monthly AI Reports",
    description: "Receive deep financial insights and saving recommendations generated by advanced AI every month.",
    icon: LineChart,
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
  },
  {
    title: "Automated Email Deliveries",
    description: "Get your financial summaries delivered straight to your inbox without lifting a finger.",
    icon: Mail,
    color: "text-amber-500",
    bgColor: "bg-amber-500/10",
  },
  {
    title: "Bank-Grade Security",
    description: "Your financial data is encrypted and secure. We use industry standards to keep your data safe.",
    icon: ShieldCheck,
    color: "text-rose-500",
    bgColor: "bg-rose-500/10",
  },
];

const Features = () => {
  return (
    <section className="py-24 bg-muted/30">
      <div className="container mx-auto px-6">
        <div className="text-center max-w-2xl mx-auto mb-16">
          <h2 className="text-3xl md:text-4xl font-bold tracking-tight mb-4">Everything you need to manage finances</h2>
          <p className="text-muted-foreground text-lg">
            Powerful tools designed to give you complete visibility and control over your money.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              className="group p-8 rounded-2xl bg-background border border-border/50 shadow-sm hover:shadow-md transition-all duration-300 hover:-translate-y-1"
            >
              <div className={cn("w-12 h-12 rounded-xl flex items-center justify-center mb-6 transition-colors", feature.bgColor)}>
                <feature.icon className={cn("w-6 h-6", feature.color)} />
              </div>
              <h3 className="text-xl font-semibold mb-3">{feature.title}</h3>
              <p className="text-muted-foreground leading-relaxed">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;
